title: Hackathon Demo
email: g.kaufmann@htl-neufelden.at
description: > # this means to ignore newlines until "baseurl:"
  Sharpen your coding skills in this hackathon.
baseurl: ""
url: "https://kfm9.github.io/ghedu-pages-jekyll"
twitter_username: kfm9
github_username:  kfm9
baseurl: /ghedu-pages-jekyll
